---
all:
  vars:
    cartridge_app_name: myapp
    cartridge_package_path: ./myapp-0.1.0.0.x86_64.tar.gz
    cartridge_cluster_cookie: secret-cookie

    # may be useful for vagrant
    ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
    ansible_ssh_common_args: '-o IdentitiesOnly=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'

  hosts:
    route-1:
      config:
        advertise_uri: '172.19.0.2:3301'
        http_port: 8181

    storage-1:
      config:
        advertise_uri: '172.19.0.2:3302'
        http_port: 8282

    route-2:
      config:
        advertise_uri: '172.19.0.3:3303'
        http_port: 8383

    storage-2-replica:
      config:
        advertise_uri: '172.19.0.3:3304'
        http_port: 8484

  children:
    # group instances by machines
    machine_1:
      vars:
        # first machine address and connection opts
        ansible_host: 172.19.0.2
        ansible_user: vagrant

      hosts:  # instances to be started on this machine
        route-1:
        storage-1:

    # group instances by replicasets
    replicaset_route_1:
      hosts:
        route-1:
        route-2:
      vars:
        replicaset_alias: Route
        roles:
          - vshard-router
          - failover-coordinator
        failover_priority:
          - route-1
          - route-2

    storage_1_replicaset:  # replicaset storage-1
      hosts:  # instances
        storage-1:
        storage-2-replica:
      vars:
        # replicaset configuration
        replicaset_alias: Replica
        roles:
          - 'vshard-storage'
        failover_priority:
          - storage-1
          - storage-2-replica

    machine_2:
      vars:
        # first machine address and connection opts
        ansible_host: 172.19.0.3
        ansible_user: vagrant

      hosts:  # instances to be started on this machine
        route-2:
        storage-2-replica:

    # group instances by replicasets
    replicaset_route_2:
      hosts:
        route-1:
        route-2:
      vars:
        replicaset_alias: Route
        roles:
          - vshard-router
          - failover-coordinator
        failover_priority:
          - route-1
          - route-2

    storage_2_replicaset:  # replicaset storage-1
      hosts:  # instances
        storage-1:
        storage-2-replica:
      vars:
        # replicaset configuration
        replicaset_alias: Replica
        roles:
          - 'vshard-storage'
        failover_priority:
          - storage-1
          - storage-2-replica
